install.packages("robotstxt")
library(robotstxt)
path = paths_allowed("https://www.samco.in/knowledge-center/articles/best-mnc-stocks-to-buy-in-india/")

#Reading the website
library(rvest)
web = read_html("https://www.samco.in/knowledge-center/articles/best-mnc-stocks-to-buy-in-india/")
library(dplyr)
Company_Name<- web%>%html_nodes(".tg-amwm+ .tg-baqh")%>%html_text()
View(Company_Name)
BSE_Scrip_Code<- web%>%html_nodes(".tg-baqh:nth-child(3)")%>%html_text()
View(BSE_Scrip_Code)
NSE_Symbol<- web%>%html_nodes(".tg-baqh:nth-child(4)")%>%html_text()
View(NSE_Symbol)
Rating<- web%>%html_nodes(".tg-baqh:nth-child(5)")%>%html_text()
View(Rating)
CMP<- web%>%html_nodes(".tg-baqh:nth-child(6)")%>%html_text()
View(CMP)
Industry<- web%>%html_nodes(".tg-baqh:nth-child(7)")%>%html_text()
View(Industry)
mnc.data<- data.frame(Company_Name,BSE_Scrip_Code,NSE_Symbol,Rating,CMP,Industry)
View(mnc.data)
write.csv(mnc.data,"webscrapping.csv")
dim(mnc.data)
str(mnc.data)
